-- Migration: Seed vineyard seasonal task templates
-- These are default task templates for each vineyard seasonal stage
-- Based on knowledge from docs/04-product/knowledgebase/seasonal/*.md

-- DORMANT STAGE TASKS
INSERT INTO task_template (id, user_id, vineyard_id, stage, entity_type, wine_type, name, description, frequency, frequency_count, frequency_unit, default_enabled, is_archived, sort_order, created_at, updated_at) VALUES
  ('vt_dormant_pruning', '', 'default', 'dormant', 'block', NULL, 'Complete winter pruning', 'Prune as late as practical before budbreak to reduce trunk disease risk. Prune cold-hardy varieties first, tender vinifera last.', 'once', NULL, NULL, TRUE, FALSE, 1, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_dormant_wound_protection', '', 'default', 'dormant', 'block', NULL, 'Apply wound protection', 'Apply wound protectant (VitiSeal, Trichoderma, or fungicide) to large pruning cuts same day. Essential for trunk disease prevention.', 'once', NULL, NULL, TRUE, FALSE, 2, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_dormant_bud_assessment', '', 'default', 'dormant', 'block', NULL, 'Assess bud damage after cold events', 'After temps below 0°F, collect 100 buds and check viability. Green tissue = alive, brown/black = dead. Adjust pruning accordingly.', 'once', NULL, NULL, TRUE, FALSE, 3, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_dormant_trellis_repair', '', 'default', 'dormant', 'block', NULL, 'Inspect and repair trellis', 'Check wire tension (~250 lbs), post integrity, end posts and anchors. Complete repairs before spring demands arrive.', 'once', NULL, NULL, TRUE, FALSE, 4, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_dormant_debris_removal', '', 'default', 'dormant', 'block', NULL, 'Remove pruning debris', 'Remove infected wood from vineyard. Burn, bury, or hot-compost. Do not leave diseased wood on ground—it sporulates for years.', 'once', NULL, NULL, TRUE, FALSE, 5, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_dormant_lime_sulfur', '', 'default', 'dormant', 'block', NULL, 'Apply dormant lime sulfur spray', 'Apply before any green tissue visible. Targets overwintering powdery mildew, Phomopsis, anthracnose, scale. Never within 30 days of oil.', 'once', NULL, NULL, TRUE, FALSE, 6, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_dormant_oil_spray', '', 'default', 'dormant', 'block', NULL, 'Apply dormant oil spray', 'Apply 2-4% concentration when temps above 40°F for 24 hours. Smothers overwintering mites, scale, aphid eggs.', 'once', NULL, NULL, TRUE, FALSE, 7, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_dormant_rodent_control', '', 'default', 'dormant', 'block', NULL, 'Install rodent protection', 'Install hardware cloth cylinders (1/4-inch mesh, 18-24" high, buried 6"). Check after heavy snows. Voles gnaw bark below ground level.', 'once', NULL, NULL, TRUE, FALSE, 8, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000)
ON CONFLICT (id) DO NOTHING;

-- BUD BREAK STAGE TASKS
INSERT INTO task_template (id, user_id, vineyard_id, stage, entity_type, wine_type, name, description, frequency, frequency_count, frequency_unit, default_enabled, is_archived, sort_order, created_at, updated_at) VALUES
  ('vt_budbreak_finish_pruning', '', 'default', 'bud_break', 'block', NULL, 'Complete any remaining pruning', 'Finish before sap flow begins (soil temps 45-48°F). Position cuts so sap flows away from retained buds.', 'once', NULL, NULL, TRUE, FALSE, 1, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_budbreak_frost_protection', '', 'default', 'bud_break', 'block', NULL, 'Implement frost protection measures', 'Clear cold air drainage paths. Mow cover crops short. Monitor forecasts closely—wool buds tolerate 25°F, green tip only 28°F.', 'daily', 1, 'days', TRUE, FALSE, 2, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_budbreak_first_fungicide', '', 'default', 'bud_break', 'block', NULL, 'Apply first fungicide spray', 'Begin when shoots reach 1-3 inches. Critical for Phomopsis in humid climates. Cannot skip this timing.', 'once', NULL, NULL, TRUE, FALSE, 3, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_budbreak_pest_scout', '', 'default', 'bud_break', 'block', NULL, 'Scout for early season pests', 'Check for cutworms (hollowed buds), grape flea beetle, climbing cutworm. Examine 5 buds/vine on 20 vines when temps above 65°F.', 'weekly', 1, 'weeks', TRUE, FALSE, 4, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_budbreak_pheromone_traps', '', 'default', 'bud_break', 'block', NULL, 'Deploy pheromone traps', 'Place grape berry moth traps at wooded vineyard edges. First-generation adults emerge at 200-250 GDD (base 50°F).', 'once', NULL, NULL, TRUE, FALSE, 5, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_budbreak_shoot_evaluation', '', 'default', 'bud_break', 'block', NULL, 'Begin evaluating shoot density', 'Note fruitful vs unfruitful shoots. Target 5-6 shoots per foot of cordon. Actual thinning waits until shoots reach 5-6 inches.', 'once', NULL, NULL, TRUE, FALSE, 6, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000)
ON CONFLICT (id) DO NOTHING;

-- FLOWERING STAGE TASKS
INSERT INTO task_template (id, user_id, vineyard_id, stage, entity_type, wine_type, name, description, frequency, frequency_count, frequency_unit, default_enabled, is_archived, sort_order, created_at, updated_at) VALUES
  ('vt_flowering_shoot_thin', '', 'default', 'flowering', 'block', NULL, 'Complete shoot thinning', 'Must finish before shoots exceed 10-12 inches and lignify. Remove trunk suckers, doubles, wrong positions, excess unfruitful shoots.', 'once', NULL, NULL, TRUE, FALSE, 1, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_flowering_disease_spray', '', 'default', 'flowering', 'block', NULL, 'Apply critical disease sprays', 'Most important spray window of the season. 7-10 day intervals from pre-bloom through 4 weeks post-bloom. Protect clusters through vulnerable period.', 'weekly', 1, 'weeks', TRUE, FALSE, 2, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_flowering_petiole_sample', '', 'default', 'flowering', 'block', NULL, 'Collect petiole tissue samples', 'Sample at 50-80% cap fall. 60-100 petioles from leaves opposite lowest flower cluster. Check B and Zn status critical for fertilization.', 'once', NULL, NULL, TRUE, FALSE, 3, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_flowering_botrytis_spray', '', 'default', 'flowering', 'block', NULL, 'Apply Botrytis spray at 80% cap fall', 'Botrytis infects through cap scars. Apply Switch, Elevate, or Pristine directly to clusters. Establishes latent infections if missed.', 'once', NULL, NULL, TRUE, FALSE, 4, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_flowering_canopy_manage', '', 'default', 'flowering', 'block', NULL, 'Continue canopy management', 'Tuck shoots into catch wires on VSP systems. Position before tendrils attach. Expect 2-3 passes during rapid growth.', 'weekly', 1, 'weeks', TRUE, FALSE, 5, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000)
ON CONFLICT (id) DO NOTHING;

-- FRUIT SET STAGE TASKS
INSERT INTO task_template (id, user_id, vineyard_id, stage, entity_type, wine_type, name, description, frequency, frequency_count, frequency_unit, default_enabled, is_archived, sort_order, created_at, updated_at) VALUES
  ('vt_fruitset_shoot_position', '', 'default', 'fruit_set', 'block', NULL, 'Complete shoot positioning', 'Begin 1-2 weeks after fruit set when shoots movable without breakage. For VSP, tuck upward; high-wire, comb downward.', 'once', NULL, NULL, TRUE, FALSE, 1, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_fruitset_assess_set', '', 'default', 'fruit_set', 'block', NULL, 'Assess fruit set disorders', 'Check for coulure (complete flower drop) and millerandage (uneven berry sizes) 10-12 days after full bloom. Note for future management.', 'once', NULL, NULL, TRUE, FALSE, 2, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_fruitset_leaf_removal', '', 'default', 'fruit_set', 'block', NULL, 'Begin fruit zone leaf removal', 'Remove 2-3 basal leaves per shoot on morning-sun side when berries reach pea size (7mm). Creates 40-60% cluster exposure.', 'once', NULL, NULL, TRUE, FALSE, 3, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_fruitset_first_hedge', '', 'default', 'fruit_set', 'block', NULL, 'First hedging pass', 'Wait until 3-4 weeks post-bloom minimum. Hedge ~1 foot above upper wires, leaving shoots at least 3 feet after cutting.', 'once', NULL, NULL, TRUE, FALSE, 4, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_fruitset_gbm_scout', '', 'default', 'fruit_set', 'block', NULL, 'Scout for grape berry moth', 'Begin 10 days post-bloom. Look for webbing and reddish-purple entry holes. Treatment threshold: 3% damaged clusters.', 'weekly', 1, 'weeks', TRUE, FALSE, 5, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_fruitset_leafhopper_scout', '', 'default', 'fruit_set', 'block', NULL, 'Scout for leafhoppers', 'Count nymphs on undersides of basal leaves 10 days after bloom. Threshold: 5 nymphs per leaf for first generation.', 'weekly', 1, 'weeks', TRUE, FALSE, 6, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_fruitset_cluster_thin', '', 'default', 'fruit_set', 'block', NULL, 'Evaluate cluster thinning needs', 'Use 2-1-None rule: shoots >20" keep 2 clusters, 8-20" keep 1, <8" keep none. Target 16-18 leaves per cluster.', 'once', NULL, NULL, TRUE, FALSE, 7, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000)
ON CONFLICT (id) DO NOTHING;

-- VERAISON STAGE TASKS
INSERT INTO task_template (id, user_id, vineyard_id, stage, entity_type, wine_type, name, description, frequency, frequency_count, frequency_unit, default_enabled, is_archived, sort_order, created_at, updated_at) VALUES
  ('vt_veraison_stop_leaf_removal', '', 'default', 'veraison', 'block', NULL, 'Stop leaf removal', 'Leaves removed after color change expose fruit to sunburn within minutes. Berries need 7 days to acclimate to new exposure.', 'once', NULL, NULL, TRUE, FALSE, 1, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_veraison_bird_netting', '', 'default', 'veraison', 'block', NULL, 'Install bird netting', 'Install at first signs of color change, not after damage appears. Side netting uses less material and allows spray access.', 'once', NULL, NULL, TRUE, FALSE, 2, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_veraison_resume_irrigation', '', 'default', 'veraison', 'block', NULL, 'Resume moderate irrigation', 'Apply 50-60% of full vine demand through harvest. Support sugar loading. Severe deficit delays sugar accumulation.', 'daily', 1, 'days', TRUE, FALSE, 3, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_veraison_begin_sampling', '', 'default', 'veraison', 'block', NULL, 'Begin weekly Brix sampling', 'Start when berries reach ~15°Brix. Sample 100-200 berries randomly. Track trends over time, not single measurements.', 'weekly', 1, 'weeks', TRUE, FALSE, 4, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_veraison_remove_green', '', 'default', 'veraison', 'block', NULL, 'Remove remaining green clusters', 'At 90% veraison, remove any green/pink clusters that lagged. They won''t catch up and will dilute quality.', 'once', NULL, NULL, TRUE, FALSE, 5, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_veraison_stop_sulfur', '', 'default', 'veraison', 'block', NULL, 'Stop sulfur applications', 'Sulfur residues can cause hydrogen sulfide during fermentation. Switch to other materials for late-season powdery mildew.', 'once', NULL, NULL, TRUE, FALSE, 6, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000)
ON CONFLICT (id) DO NOTHING;

-- RIPENING STAGE TASKS
INSERT INTO task_template (id, user_id, vineyard_id, stage, entity_type, wine_type, name, description, frequency, frequency_count, frequency_unit, default_enabled, is_archived, sort_order, created_at, updated_at) VALUES
  ('vt_ripening_intensive_sample', '', 'default', 'ripening', 'block', NULL, 'Increase sampling frequency', 'Sample twice weekly approaching targets, daily in final week. Measure Brix, pH, TA. Taste systematically.', 'daily', 1, 'days', TRUE, FALSE, 1, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_ripening_sensory_assess', '', 'default', 'ripening', 'block', NULL, 'Conduct sensory assessments', 'Evaluate berry sweetness, skin tannin texture, seed hardness/flavor, aromatic development. Ripe seeds crack audibly when bitten.', 'daily', 1, 'days', TRUE, FALSE, 2, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_ripening_botrytis_manage', '', 'default', 'ripening', 'block', NULL, 'Monitor for Botrytis and sour rot', 'Scout after any rain. Botrytis: gray fuzzy mold. Sour rot: vinegar smell, requires flies. Remove affected clusters immediately.', 'daily', 1, 'days', TRUE, FALSE, 3, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_ripening_weather_monitor', '', 'default', 'ripening', 'block', NULL, 'Monitor weather forecasts daily', 'Optimal window often only 48-72 hours. Rain forecast may justify picking at 22°Brix rather than gambling on 24°Brix.', 'daily', 1, 'days', TRUE, FALSE, 4, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_ripening_prepare_harvest', '', 'default', 'ripening', 'block', NULL, 'Prepare for harvest', 'Have equipment cleaned and help arranged 2 weeks before anticipated harvest. Know contingency plan for weather scenarios.', 'once', NULL, NULL, TRUE, FALSE, 5, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000)
ON CONFLICT (id) DO NOTHING;

-- HARVEST STAGE TASKS
INSERT INTO task_template (id, user_id, vineyard_id, stage, entity_type, wine_type, name, description, frequency, frequency_count, frequency_unit, default_enabled, is_archived, sort_order, created_at, updated_at) VALUES
  ('vt_harvest_sampling', '', 'default', 'harvest', 'block', NULL, 'Final harvest sampling', 'Use 3-5-7 protocol: 3 rows in, 3 vines down, sample top/middle/base. 100-200 berries per block.', 'daily', 1, 'days', TRUE, FALSE, 1, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_harvest_pick_morning', '', 'default', 'harvest', 'block', NULL, 'Harvest during cool morning hours', 'Begin before sunrise, finish by late morning. Cool fruit (<68°F) favors yeast over bacteria. Night harvest for aromatics.', 'once', NULL, NULL, TRUE, FALSE, 2, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_harvest_field_sort', '', 'default', 'harvest', 'block', NULL, 'Field sort aggressively', 'Never harvest clusters you wouldn''t eat unwashed. Remove Botrytis, sour rot, bird damage, insects. MOG below 1%.', 'daily', 1, 'days', TRUE, FALSE, 3, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_harvest_temp_manage', '', 'default', 'harvest', 'block', NULL, 'Manage fruit temperature', 'Never let fruit sit in sun. Keep in shade, covered. Process same day, ideally within hours. Refrigerate if overnight storage needed.', 'daily', 1, 'days', TRUE, FALSE, 4, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_harvest_record', '', 'default', 'harvest', 'block', NULL, 'Record harvest data', 'Document date, variety, Brix, pH, TA, weather, total yield, fruit condition. Calculate yield per vine.', 'once', NULL, NULL, TRUE, FALSE, 5, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000)
ON CONFLICT (id) DO NOTHING;

-- POST-HARVEST STAGE TASKS
INSERT INTO task_template (id, user_id, vineyard_id, stage, entity_type, wine_type, name, description, frequency, frequency_count, frequency_unit, default_enabled, is_archived, sort_order, created_at, updated_at) VALUES
  ('vt_postharvest_irrigate', '', 'default', 'post_harvest', 'block', NULL, 'Apply post-harvest irrigation', 'Apply at least 10% of seasonal irrigation. 10-20 gallons per vine. Support photosynthesis and root growth. Essential, not optional.', 'once', NULL, NULL, TRUE, FALSE, 1, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_postharvest_potassium', '', 'default', 'post_harvest', 'block', NULL, 'Apply potassium fertilizer', 'K uptake diminishes 30 days after harvest. Each ton of grapes removes ~5 lbs K. Apply within 2 weeks of harvest.', 'once', NULL, NULL, TRUE, FALSE, 2, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_postharvest_disease_spray', '', 'default', 'post_harvest', 'block', NULL, 'Continue disease management', 'Protect leaves for photosynthesis. Reduce overwintering inoculum. Vineyards spraying through Sept had 28x fewer mildew structures.', 'biweekly', 2, 'weeks', TRUE, FALSE, 3, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_postharvest_mummy_removal', '', 'default', 'post_harvest', 'block', NULL, 'Remove mummified fruit', 'Most important sanitation step for black rot. Mummies in trellis far worse than on ground. Also remove second crop clusters.', 'once', NULL, NULL, TRUE, FALSE, 4, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_postharvest_trunk_sanitation', '', 'default', 'post_harvest', 'block', NULL, 'Complete trunk disease sanitation', 'Remove cankered wood before first fall rain. Cut 4-12 inches beyond visible infection. Remove from vineyard entirely.', 'once', NULL, NULL, TRUE, FALSE, 5, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_postharvest_cover_crop', '', 'default', 'post_harvest', 'block', NULL, 'Seed winter cover crop', 'Seed after harvest with irrigation or expected rain. Vigorous vineyards: no legumes. Weak vineyards: 20-30% legume blend.', 'once', NULL, NULL, TRUE, FALSE, 6, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_postharvest_hilling', '', 'default', 'post_harvest', 'block', NULL, 'Hill up graft unions (cold climates)', 'Create 3-4 inch soil mound above graft union before ground freezes. Keeps tissue 22°F warmer than air temperature.', 'once', NULL, NULL, TRUE, FALSE, 7, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_postharvest_rodent_prep', '', 'default', 'post_harvest', 'block', NULL, 'Prepare for rodent control', 'Mow vegetation short around trunks. Maintain bare strip 6-12" around bases. Remove debris piles before snow arrives.', 'once', NULL, NULL, TRUE, FALSE, 8, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_postharvest_trellis_assess', '', 'default', 'post_harvest', 'block', NULL, 'Assess trellis and infrastructure', 'Walk every row, note needed repairs. Fix anything threatening vine support through winter. Defer other repairs to pruning time.', 'once', NULL, NULL, TRUE, FALSE, 9, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000),
  ('vt_postharvest_winterize', '', 'default', 'post_harvest', 'block', NULL, 'Winterize irrigation system', 'Drain all lines before hard freeze. Compressed air blow-out essential for drip. Disconnect backflow preventers, store indoors.', 'once', NULL, NULL, TRUE, FALSE, 10, extract(epoch from now()) * 1000, extract(epoch from now()) * 1000)
ON CONFLICT (id) DO NOTHING;
